In [4]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import gc
import math

np.random.seed(1)
tf.keras.backend.set_floatx('float64')
tf.random.set_seed(5)
tf.random.shuffle(tf.range(5))

samples, timesteps, features = 3, 10, 2
inputs = np.random.random([samples, timesteps, features]).astype(np.float64)

model = tf.keras.models.Sequential()

output = model(inputs)

print(output)
# Given inputs are radius of a circle, convert them to the area of a circle
model.add(tf.keras.layers.Lambda(lambda x: (math.pi * x) ** 2, input_shape=(timesteps, features)))
output = model(inputs)

print(output)

tf.Tensor(
[[[4.17022005e-01 7.20324493e-01]
  [1.14374817e-04 3.02332573e-01]
  [1.46755891e-01 9.23385948e-02]
  [1.86260211e-01 3.45560727e-01]
  [3.96767474e-01 5.38816734e-01]
  [4.19194514e-01 6.85219500e-01]
  [2.04452250e-01 8.78117436e-01]
  [2.73875932e-02 6.70467510e-01]
  [4.17304802e-01 5.58689828e-01]
  [1.40386939e-01 1.98101489e-01]]

 [[8.00744569e-01 9.68261576e-01]
  [3.13424178e-01 6.92322616e-01]
  [8.76389152e-01 8.94606664e-01]
  [8.50442114e-02 3.90547832e-02]
  [1.69830420e-01 8.78142503e-01]
  [9.83468338e-02 4.21107625e-01]
  [9.57889530e-01 5.33165285e-01]
  [6.91877114e-01 3.15515631e-01]
  [6.86500928e-01 8.34625672e-01]
  [1.82882773e-02 7.50144315e-01]]

 [[9.88861089e-01 7.48165654e-01]
  [2.80443992e-01 7.89279328e-01]
  [1.03226007e-01 4.47893526e-01]
  [9.08595503e-01 2.93614148e-01]
  [2.87775339e-01 1.30028572e-01]
  [1.93669579e-02 6.78835533e-01]
  [2.11628116e-01 2.65546659e-01]
  [4.91573159e-01 5.33625451e-02]
  [5.74117605e-01 1.46728575e-01]